apiVersion: apps/v1
kind: Deployment
metadata:
  name: abnormality-service
  labels:
    app: abnormality-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abnormality-service
  template:
    metadata:
      labels:
        app: abnormality-service
    spec:
      containers:
        - name: abnormality-service
          image: docker.io/brycepillwein/abnormality-service:latest
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: MQTT_BROKER_URL
              value: "mqtt://broker.hivemq.com:1883"
            - name: MQTT_TOPIC
              value: "tempotrackvital0192837465/health/new"
            - name: PROFILE_SERVICE_URL
              value: "http://profile-service:3001"
            - name: ALERT_SERVICE_URL
              value: "http://alert-service:3003/v1/alert"
---
apiVersion: v1
kind: Service
metadata:
  name: abnormality-service
spec:
  selector:
    app: abnormality-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
