apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  labels:
    app: alert-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
        - name: alert-service
          image: docker.io/brycepillwein/alert-service:latest
          ports:
            - containerPort: 3003
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: PORT
              value: "3003"
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
spec:
  selector:
    app: alert-service
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP
