apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-gateway
  labels:
    app: frontend-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-gateway
  template:
    metadata:
      labels:
        app: frontend-gateway
    spec:
      containers:
        - name: frontend-gateway
          image: brycepillwein/frontend-gateway:latest-1
          imagePullPolicy: Always
          ports:
            - containerPort: 3006
          env:
            - name: PORT
              value: "3006"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3006
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-gateway
spec:
  type: LoadBalancer
  selector:
    app: frontend-gateway
  ports:
    - port: 80
      targetPort: 3006
