apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: docker.io/brycepillwein/ingestion-service:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: MQTT_BROKER_URL
              value: "mqtt://broker.hivemq.com:1883"
            - name: MQTT_TOPIC
              value: "tempotrackvital0192837465/health/new"
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  selector:
    app: ingestion-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
