apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  labels:
    app: monitoring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
        - name: monitoring-service
          image: docker.io/brycepillwein/monitoring-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3007
          env:
            - name: PORT
              value: "3007"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3007
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  selector:
    app: monitoring-service
  ports:
    - port: 3007
      targetPort: 3007
  type: ClusterIP
