apiVersion: v1
kind: Service
metadata:
  name: node-calculator-service
spec:
  type: NodePort
  selector:
    app: node-calculator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
