apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-calculator
  template:
    metadata:
      labels:
        app: node-calculator
    spec:
      containers:
        - name: node-calculator
          image: node-calculator:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo-service:27017/?authSource=admin"
                
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /calculator/history
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
