apiVersion: apps/v1
kind: Deployment
metadata:
  name: gscloud-monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gscloud-monitor
  template:
    metadata:
      labels:
        app: gscloud-monitor
    spec:
      containers:
        - name: gscloud-monitor
          image: brycepillwein/gscloud-monitor:latest
          ports:
            - containerPort: 3000

          # Health Probes
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          # Resources for Monitoring
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
