apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-gscloud-monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-gscloud-monitor
  template:
    metadata:
      labels:
        app: node-gscloud-monitor
    spec:
      containers:
        - name: node-gscloud-monitor
          image: <your-dockerhub-username>/node-gscloud-monitor:1.0
          ports:
            - containerPort: 3000

          # Health check probes
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          # Resource usage monitoring (for GCP dashboards)
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
