apiVersion: v1
kind: Service
metadata:
  name: gscloud-monitor-service
spec:
  type: LoadBalancer
  selector:
    app: gscloud-monitor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000